### ISSUE TITLE
No intimation on draw and no restart button after a drawn match

### ISSUE THREAD

**Issue by BaraniVA** [iamparas0/TIC-TAC-TOE#1]
**Issue:**
- There is no intimation when the match ends in a draw.
- There is no restart button available after the match has been drawn.

**Steps to reproduce:**
1. Play the game until it results in a draw.
2. Observe that there is no message indicating the draw.
3. Notice that there is no option to restart the game after a draw.

**Expected behavior:**
- A message should be displayed indicating that the match has ended in a draw.
- A restart button should be available to start a new game after a draw.

**Additional context:**
![image](https://github.com/user-attachments/assets/ef293874-9ffd-466f-a03b-336944ff4cba)

**Comment by BaraniVA** [comment]
Please add the label for GSSoC 2024 Extd. and assign this issue to me. I would like to work on fixing it.

**Comment by BaraniVA** [comment]
please assign this for me

**Comment by iamparas0** [comment]
> **Issue:**
> 
> * There is no intimation when the match ends in a draw.
> * There is no restart button available after the match has been drawn.
> 
> **Steps to reproduce:**
> 
> 1. Play the game until it results in a draw.
> 2. Observe that there is no message indicating the draw.
> 3. Notice that there is no option to restart the game after a draw.
> 
> **Expected behavior:**
> 
> * A message should be displayed indicating that the match has ended in a draw.
> * A restart button should be available to start a new game after a draw.
> 
> **Additional context:** ![image](https://private-user-images.githubusercontent.com/110531153/372466549-ef293874-9ffd-466f-a03b-336944ff4cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjEyNzMsIm5iZiI6MTcyODA2MDk3MywicGF0aCI6Ii8xMTA1MzExNTMvMzcyNDY2NTQ5LWVmMjkzODc0LTlmZmQtNDY2Zi1hMDNiLTMzNjk0NGZmNGNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjU2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTA1NWMzYWU4YjgxMzhhYWU3Y2ExNmZiZDcwODlhOTQzNWZmY2I1NWNmMjdlZWQ4OGMxYzBjM2I3YWFjZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mmVe_Hy8Wz26XqikkEVosgL1JyScqMjtGzLOPvUbzsw)

Go for it , please attach a demo video of before and after

**Comment by Sarthakkashyapp** [comment]
Please assign this issue to me @iamparas0

**Comment by iamparas0** [comment]
> > **Issue:**
> > 
> > * There is no intimation when the match ends in a draw.
> > * There is no restart button available after the match has been drawn.
> > 
> > **Steps to reproduce:**
> > 
> > 1. Play the game until it results in a draw.
> > 2. Observe that there is no message indicating the draw.
> > 3. Notice that there is no option to restart the game after a draw.
> > 
> > **Expected behavior:**
> > 
> > * A message should be displayed indicating that the match has ended in a draw.
> > * A restart button should be available to start a new game after a draw.
> > 
> > **Additional context:** ![image](https://private-user-images.githubusercontent.com/110531153/372466549-ef293874-9ffd-466f-a03b-336944ff4cba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjEyNzMsIm5iZiI6MTcyODA2MDk3MywicGF0aCI6Ii8xMTA1MzExNTMvMzcyNDY2NTQ5LWVmMjkzODc0LTlmZmQtNDY2Zi1hMDNiLTMzNjk0NGZmNGNiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjU2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTA1NWMzYWU4YjgxMzhhYWU3Y2ExNmZiZDcwODlhOTQzNWZmY2I1NWNmMjdlZWQ4OGMxYzBjM2I3YWFjZThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mmVe_Hy8Wz26XqikkEVosgL1JyScqMjtGzLOPvUbzsw)
> 
> Go for it , please attach a demo video of before and after



> please assign this for me

great work hope you enjoyed while contributing , good luck for future!
