### ISSUE TITLE
The mouse pointer on the restart button should be cursor

### ISSUE THREAD

**Issue by krishnaagrawal74** [iamparas0/TIC-TAC-TOE#106]
![image](https://github.com/user-attachments/assets/a504cb93-fbf8-4941-8404-32e844215d96)

**Comment by vundrakondaIndira** [comment]
hello @iamparas0 

could you please assign this task to me I would like to work on this.

**Comment by krishnaagrawal74** [comment]
@iamparas0 please assign it to me

**Comment by iamparas0** [comment]
> ![image](https://private-user-images.githubusercontent.com/173372944/373966835-a504cb93-fbf8-4941-8404-32e844215d96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODMzODYsIm5iZiI6MTcyODM4MzA4NiwicGF0aCI6Ii8xNzMzNzI5NDQvMzczOTY2ODM1LWE1MDRjYjkzLWZiZjgtNDk0MS04NDA0LTMyZTg0NDIxNWQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMDI0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjlmNDgxMDU1NTM2NTIyZTlhYTU3MTY2ZWJmMWJiOTFhNzEzYjYwZTNiMWU3YmUwYzVhNGY3Y2Q4MDY3ZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qhpM1rG2dGLiI1GMYJ8-3Er9eot_ttlU1fgpZMGcq6E)

not neccesary
