### ISSUE TITLE
Missing restart option when game is tie

### ISSUE THREAD

**Issue by ananyag309** [iamparas0/TIC-TAC-TOE#12]
Display "Play again" and add reset button which is missing
![tie](https://github.com/user-attachments/assets/c1751273-fc08-47e0-83c2-70803376678a)

**Comment by Mirnalkishor** [comment]
I want to work on this issue

**Comment by Uhalatha5** [comment]
Hi, I would love to contribute to enhancing the UI using Tailwind CSS and adding react-toasts as a GSSOC'24 contributor. Could you please assign this issue to me? I’m excited to improve the user experience and make the game more interactive. Thanks!

**Comment by Payel647** [comment]
I want to work on this issue

**Comment by Jerusha547** [comment]
I want to work on this issue. Assign it to me

**Comment by Shukla000** [comment]
Please assign me the task.
