### ISSUE TITLE
Improve the Home Page UI for Tic Tac Toe

### ISSUE THREAD

**Issue by Hemraj-7** [iamparas0/TIC-TAC-TOE#123]
I want to improve the Home Page UI for Tic Tac Toe

![Screenshot 2024-10-07 173703](https://github.com/user-attachments/assets/8e243056-d5d3-4fb9-89eb-012677a4a726)

Please assign me, I will make the best best UI for the Tic Tac Toe home page!

**Comment by Ek-ta-bharti** [comment]
I would like to work on this. Please assign this to me.
