### ISSUE TITLE
Add Draw Feature to Tic Tac Toe Game

### ISSUE THREAD

**Issue by T-Fathima** [iamparas0/TIC-TAC-TOE#125]
Currently, the Tic Tac Toe game does not handle the draw condition. This feature is essential for informing players when all cells are filled, and no player has won. Implementing this feature will enhance the game's functionality and user experience.
**Benefits:**
Enhances the game's functionality by properly handling the draw condition.
Improves user experience by providing clear feedback when the game ends in a draw.

**I would like to work on this issue.**
@iamparas0 **Please assign it to me under gssoc-ext'24 and hactoberfest**
![image](https://github.com/user-attachments/assets/a4883eca-73d4-44e1-aaa0-7cb29240391d)

**Comment by iamparas0** [comment]
> Currently, the Tic Tac Toe game does not handle the draw condition. This feature is essential for informing players when all cells are filled, and no player has won. Implementing this feature will enhance the game's functionality and user experience. **Benefits:** Enhances the game's functionality by properly handling the draw condition. Improves user experience by providing clear feedback when the game ends in a draw.
> 
> **I would like to work on this issue.** @iamparas0 **Please assign it to me under gssoc-ext'24 and hactoberfest** ![image](https://private-user-images.githubusercontent.com/148070120/374180498-a4883eca-73d4-44e1-aaa0-7cb29240391d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODMyMDcsIm5iZiI6MTcyODM4MjkwNywicGF0aCI6Ii8xNDgwNzAxMjAvMzc0MTgwNDk4LWE0ODgzZWNhLTczZDQtNDRlMS1hYWEwLTdjYjI5MjQwMzkxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMDIxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWRjYWFhNmE5NmM4M2VhNzNiM2JkNDdmNzBjMGVkNjdlM2E1OWYyNGQ4MDc0MjE3NmVmMTdjMTE1YTJmZDAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CpbxhuxxJdhzYFWAWiQfEWZPoGWXbbhQ1FF7ASAIUds)

its already have
