### ISSUE TITLE
Enhancing Readme.md

### ISSUE THREAD

**Issue by neeru24** [iamparas0/TIC-TAC-TOE#13]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I also made the similar Tic-Tac-Toe project. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the game. 

I believe updates to Readme.md file could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by vanshikaashrma** [comment]
I’ve been exploring the project and appreciate the work done so far. I have experience with a similar Tic-Tac-Toe project and would like to propose updates to the README.md file for a clearer overview of the game.

If you’re open to it, I’d love to contribute!

**Comment by neeru24** [comment]
Can you add labels please for GSSoC-Ext and others.

**Comment by iamparas0** [comment]
> Hi,
> 
> I’ve been exploring the project and appreciate the work you’ve done so far. I also made the similar Tic-Tac-Toe project. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the game.
> 
> I believe updates to Readme.md file could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.
> 
> I’m committed to continually improving the quality of our documentation.
> 
> Thank you!

go for it!

**note :
please do not add fancy colourful boxes and extras ,  only needed things must be add like forking , pr and presentation like ss or video . Please fork and create new branch so it will not create conflicts 

good luck!

**Comment by neeru24** [comment]
> > Hi,
> > I’ve been exploring the project and appreciate the work you’ve done so far. I also made the similar Tic-Tac-Toe project. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the game.
> > I believe updates to Readme.md file could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.
> > I’m committed to continually improving the quality of our documentation.
> > Thank you!
> 
> go for it!
> 
> **note : please do not add fancy colourful boxes and extras , only needed things must be add like forking , pr and issue rules. add . Please fork and create new branch so it will not create conflicts
> 
> ##please put screenshot before pr hope you understand , good luck!

Basically, you mean
1. Steps for contributing need to be added.
2. Overview of the project 
right??

**Comment by iamparas0** [comment]
> > > Hi,
> > > I’ve been exploring the project and appreciate the work you’ve done so far. I also made the similar Tic-Tac-Toe project. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the game.
> > > I believe updates to Readme.md file could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.
> > > I’m committed to continually improving the quality of our documentation.
> > > Thank you!
> > 
> > 
> > go for it!
> > **note : please do not add fancy colourful boxes and extras , only needed things must be add like forking , pr and issue rules. add . Please fork and create new branch so it will not create conflicts
> > ##please put screenshot before pr hope you understand , good luck!
> 
> Basically, you mean
> 
> 1. Steps for contributing need to be added.
> 2. Overview of the project
>    right??

yes and look as simple as it can!

**Comment by neeru24** [comment]
> > > > Hi,
> > > > I’ve been exploring the project and appreciate the work you’ve done so far. I also made the similar Tic-Tac-Toe project. I’d like to propose an update to the README.md file to provide a more comprehensive overview of the game.
> > > > I believe updates to Readme.md file could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.
> > > > I’m committed to continually improving the quality of our documentation.
> > > > Thank you!
> > > 
> > > 
> > > go for it!
> > > **note : please do not add fancy colourful boxes and extras , only needed things must be add like forking , pr and issue rules. add . Please fork and create new branch so it will not create conflicts
> > > ##please put screenshot before pr hope you understand , good luck!
> > 
> > Basically, you mean
> > 
> > 1. Steps for contributing need to be added.
> > 2. Overview of the project
> >    right??
> 
> yes and look as simple as it can!

![Screenshot 2024-10-05 230314](https://github.com/user-attachments/assets/e986692d-e0e9-4253-a228-b5d5961688fc)
 
![Screenshot 2024-10-05 230331](https://github.com/user-attachments/assets/ab780206-e60a-4d2d-833b-23d470282105)

![image](https://github.com/user-attachments/assets/15228569-49ae-4ff7-9b95-27d1c24e352b)

**Comment by iamparas0** [comment]
great work!
