### ISSUE TITLE
Auto detecting user's systems colour mode and loading the game with that mode 

### ISSUE THREAD

**Issue by Nimit1775** [iamparas0/TIC-TAC-TOE#158]
auto detecting the systems colour mode so that the user doesnot have to change it manually , 
by this  if the user has  his device on dark mode the the game will auto load with dark mode and vice versa and the manual choosing option will of course be there too like it is already  

assign me this issue please @iamparas0

**Comment by iamparas0** [comment]
> auto detecting the systems colour mode so that the user doesnot have to change it manually , by this if the user has his device on dark mode the the game will auto load with dark mode and vice versa and the manual choosing option will of course be there too like it is already
> 
> assign me this issue please @iamparas0

Go for it please put ss before pr
