### ISSUE TITLE
Hacktoberfest amd GSSOC Ext Topic In Repository

### ISSUE THREAD

**Issue by MastanSayyad** [iamparas0/TIC-TAC-TOE#161]
Hi @iamparas0 PM this side

please add `hacktoberfest` and `gssoc-ext` topics in your repository description

![image](https://github.com/user-attachments/assets/1bbd7a2d-e167-409e-aca0-3037038e070d)

**Comment by iamparas0** [comment]
> Hi @iamparas0 PM this side
> 
> please add `hacktoberfest` and `gssoc-ext` topics in your repository description
> 
> ![image](https://private-user-images.githubusercontent.com/101971980/374692936-1bbd7a2d-e167-409e-aca0-3037038e070d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0Mzc4MDAsIm5iZiI6MTcyODQzNzUwMCwicGF0aCI6Ii8xMDE5NzE5ODAvMzc0NjkyOTM2LTFiYmQ3YTJkLWUxNjctNDA5ZS1hY2EwLTMwMzcwMzhlMDcwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQwMTMxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTc3OGM5M2UwOWYwODE1MjFjN2Y5YWE3YzdiODc3MWEzOWE5MTIxMmQ3ZjhjNjQ0OGIzNDNlZWJmZjE0OTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IVWyzoVdw3wEPtkkxGqumh8d0qMknWTuPgKaJlJrdxE)

Done
