### ISSUE TITLE
COLOUR CHANGE OF THE BOXES ON PLACING THE CURSOR 

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [iamparas0/TIC-TAC-TOE#17]
When we are placing the cursor on a specific box, there should be a slight change in colour of the box.
example: change of colour from light blue to dark to indicate that the box has already been opened and answer has been marked.
I would like the issue to be assigned to me for better development. @Damini2004 @iamparas0 
and also please mark labels for GSSoC Extd and HacktoberFest accepted or levels...

![Screenshot 2024-10-02 154810](https://github.com/user-attachments/assets/1d7e29db-0aaa-4ce3-9868-9d3383c2f3f8)

**Comment by Damini2004** [comment]
@ABHISIKTAcommits Go for it.

**Comment by sambedan1** [comment]
assign this to me

**Comment by Ashmita-15** [comment]
The issue demands change of color as we hover over the boxes from light blue to any dark color. I can easily do this. Please assign this to me! @Damini2004

**Comment by Antima2004** [comment]
please assign this to me

**Comment by ABHISIKTAcommits** [comment]
@Damini2004 It's done ... You can check

**Comment by Ishita-Si** [comment]
Assign me this task. I already did made this project so i would assist it better
heres the sample, 
![Screenshot 2024-10-02 230524](https://github.com/user-attachments/assets/acd72599-78d0-4d70-8699-ece14ae4a092)

**Comment by RanitDERIA** [comment]
I would like to work on this. Please assign this to me.

**Comment by Akanshaku** [comment]
I would like to work on this.

**Comment by AgarwalSneh** [comment]
I will really like to work on it

**Comment by Sarthakkashyapp** [comment]
Hi @iamparas0  I would like to work on this issue have done something similar before assign this issue to me.

**Comment by iamparas0** [comment]
> @Damini2004 It's done ... You can check

can you please fork the updated repository and make changes in it so i can maerge it .

**Comment by BhavikaPachauri** [comment]
I would like to work on this. Please assign this to me.

**Comment by ABHISIKTAcommits** [comment]
@iamparas0 i have already forked it
