### ISSUE TITLE
Update Footer Year to 2024

### ISSUE THREAD

**Issue by neeru24** [iamparas0/TIC-TAC-TOE#170]
I would like to address an issue in the footer of the project. Currently, the text reads "All rights reserved 2023." I propose changing it to "All rights reserved 2024" to reflect the current year and I want to change some styling of it too.

Could you please assign me this issue? I will modify it accordingly and submit a PR as soon as it's done.

Thank you!

![image](https://github.com/user-attachments/assets/df383fa5-d1d6-4ba7-8395-e5ced583ee19)

**Comment by iamparas0** [comment]
> I would like to address an issue in the footer of the project. Currently, the text reads "All rights reserved 2023." I propose changing it to "All rights reserved 2024" to reflect the current year and I want to change some styling of it too.
> 
> Could you please assign me this issue? I will modify it accordingly and submit a PR as soon as it's done.
> 
> Thank you!
> 
> ![image](https://private-user-images.githubusercontent.com/161798182/374852170-df383fa5-d1d6-4ba7-8395-e5ced583ee19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjUyNTQsIm5iZiI6MTcyODY2NDk1NCwicGF0aCI6Ii8xNjE3OTgxODIvMzc0ODUyMTcwLWRmMzgzZmE1LWQxZDYtNGJhNy04Mzk1LWU1Y2VkNTgzZWUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxNjQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2Y2ZTE5OTVmYzk3NjQzZjliNThlZDA0OTZjN2RkNGNmZWI3NzNjZjFkOGFlMWU0ZTU5NjMwOGU1Yjk0ZmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6GRYO-aldyXDQOguWh9oO0JUnyBmZD0BYlLYlR0ll_c)

Go for it

**Comment by neeru24** [comment]
> > I would like to address an issue in the footer of the project. Currently, the text reads "All rights reserved 2023." I propose changing it to "All rights reserved 2024" to reflect the current year and I want to change some styling of it too.
> > Could you please assign me this issue? I will modify it accordingly and submit a PR as soon as it's done.
> > Thank you!
> > ![image](https://private-user-images.githubusercontent.com/161798182/374852170-df383fa5-d1d6-4ba7-8395-e5ced583ee19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjUyNTQsIm5iZiI6MTcyODY2NDk1NCwicGF0aCI6Ii8xNjE3OTgxODIvMzc0ODUyMTcwLWRmMzgzZmE1LWQxZDYtNGJhNy04Mzk1LWU1Y2VkNTgzZWUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxNjQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2Y2ZTE5OTVmYzk3NjQzZjliNThlZDA0OTZjN2RkNGNmZWI3NzNjZjFkOGFlMWU0ZTU5NjMwOGU1Yjk0ZmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6GRYO-aldyXDQOguWh9oO0JUnyBmZD0BYlLYlR0ll_c)
> 
> Go for it

Hi.... Has someone done any changes to the files??? I'm not able to get code and there is written like developed by sh... something like this name in the file.. If you have link to the code, kindly share with mee.

**Comment by iamparas0** [comment]
> > > I would like to address an issue in the footer of the project. Currently, the text reads "All rights reserved 2023." I propose changing it to "All rights reserved 2024" to reflect the current year and I want to change some styling of it too.
> > > Could you please assign me this issue? I will modify it accordingly and submit a PR as soon as it's done.
> > > Thank you!
> > > ![image](https://private-user-images.githubusercontent.com/161798182/374852170-df383fa5-d1d6-4ba7-8395-e5ced583ee19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjUyNTQsIm5iZiI6MTcyODY2NDk1NCwicGF0aCI6Ii8xNjE3OTgxODIvMzc0ODUyMTcwLWRmMzgzZmE1LWQxZDYtNGJhNy04Mzk1LWU1Y2VkNTgzZWUxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxNjQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2Y2ZTE5OTVmYzk3NjQzZjliNThlZDA0OTZjN2RkNGNmZWI3NzNjZjFkOGFlMWU0ZTU5NjMwOGU1Yjk0ZmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6GRYO-aldyXDQOguWh9oO0JUnyBmZD0BYlLYlR0ll_c)
> > 
> > 
> > Go for it
> 
> Hi.... Has someone done any changes to the files??? I'm not able to get code and there is written like developed by sh... something like this name in the file.. If you have link to the code, kindly share with mee.

Put ss or something cause I have browse the link it normal
