### ISSUE TITLE
Adding the contributors page for mentioning awersome people on website who contributed in this.

### ISSUE THREAD

**Issue by tarunkumar2005** [iamparas0/TIC-TAC-TOE#175]
Adding the contributors page for mentioning awersome people on website who contributed in this.

@iamparas0 Assign this to me under gssoc 2024 ext and hacktoberfest. I will work on this issue

**Comment by iamparas0** [comment]
already have

**Comment by tarunkumar2005** [comment]
On the website i am saying it is in documentation only not on the website. @iamparas0
