### ISSUE TITLE
Enhance home page

### ISSUE THREAD

**Issue by Kajalmehta29** [iamparas0/TIC-TAC-TOE#195]
I want to make the home page more attractive using css.

Please assign this issue to e under gssoc-extd and hacktoberfest.

<img width="813" alt="Screenshot 2024-10-10 at 10 15 15 PM" src="https://github.com/user-attachments/assets/b6d1d1fa-edde-4778-985a-8937a7337891">

**Comment by skmjsourabhkumar** [comment]
@iamparas0 Hii i want to enhance the website of home page to make it more attractive 
please assing to me

**Comment by swati-204** [comment]
I want to work on the UI of this game.
can you assign this to me @iamparas0

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..
