### ISSUE TITLE
Fix JSX Syntax Error in App.js: Adjacent JSX Elements Must Be Wrapped in an Enclosing Tag

### ISSUE THREAD

**Issue by Monojit-Pal** [iamparas0/TIC-TAC-TOE#200]
In src/App.js, there is a JSX syntax error where adjacent elements are not properly enclosed in a single parent element. This leads to the build failing with the message: "Adjacent JSX elements must be wrapped in an enclosing tag." To resolve this issue, the elements need to be wrapped in a <div> or a React fragment (<>...</>). I would like to address this error and improve the component structure.
![Screenshot 2024-10-11 190218](https://github.com/user-attachments/assets/f6b53e83-89ff-43a1-bec5-b07a19b4d4cd)
@iamparas0

**Comment by iamparas0** [comment]
> In src/App.js, there is a JSX syntax error where adjacent elements are not properly enclosed in a single parent element. This leads to the build failing with the message: "Adjacent JSX elements must be wrapped in an enclosing tag." To resolve this issue, the elements need to be wrapped in a
> 
> or a React fragment (<>...</>). I would like to address this error and improve the component structure.
> ![Screenshot 2024-10-11 190218](https://private-user-images.githubusercontent.com/144504389/375772771-f6b53e83-89ff-43a1-bec5-b07a19b4d4cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjUxMjYsIm5iZiI6MTcyODY2NDgyNiwicGF0aCI6Ii8xNDQ1MDQzODkvMzc1NzcyNzcxLWY2YjUzZTgzLTg5ZmYtNDNhMS1iZWM1LWIwN2ExOWI0ZDRjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxNjQwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDhmOWZlZDY2ZDYyOGJhOWVlMGQ5N2VmZDdjYjYwZmEwYmE3YmQwYWQ2N2ViZGM1MTNmOTk2ZjU2MDVmNjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wytncBGunApWbwx68ZDpwC5LmmK0dUaqrpR9JrS07Po)
> @iamparas0

I have fixed it cause lot of people getting errors, it need to be fixed quick
