### ISSUE TITLE
give more styling to the the tic tak toe game

### ISSUE THREAD

**Issue by rutikakengal** [iamparas0/TIC-TAC-TOE#21]
more presentable and dynamic look to the game which give better user interaction

**Comment by shbhmexe** [comment]
Can you assign this work to me? And I will always contribute to any issue, cause it makes me think and grow further

**Comment by Ishita-Si** [comment]
I would like to enhance the styling , customize it to look more attractive and appealing.

**Comment by TRUPTI135** [comment]
I am really good in html would your assgn this to me

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..
