### ISSUE TITLE
 Update Navbar and Theme Toggle Button

### ISSUE THREAD

**Issue by AnushkaChouhan25** [iamparas0/TIC-TAC-TOE#223]
Propose enhancing the navbar design and replacing the theme toggle button with a proper logo-based toggle for improved aesthetics and functionality.

![image](https://github.com/user-attachments/assets/95be1fd6-d8b4-4754-a689-75fa36ef38e9)

**Comment by AnushkaChouhan25** [comment]
Hello @iamparas0,

I encountered errors in the App.js file, and despite my attempts to fix them, I couldn't resolve the issue. Some mistakes or repetitions are causing the project to fail during local execution. Could you please review the code and help identify the problem?

**Comment by KrishnaMohanty08** [comment]
@iamparas0 could assign the issue to me i would like to work on this

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
