### ISSUE TITLE
Restart Button Styling

### ISSUE THREAD

**Issue by saumyayadav25** [iamparas0/TIC-TAC-TOE#225]
Restart Button can be styled and some better transitions can also be applied on hovering.

<img width="612" alt="Screenshot 2024-10-13 at 5 46 16 PM" src="https://github.com/user-attachments/assets/6fa62d09-b127-4b5e-a86a-bc03b60d442a">

**Comment by nayakbiku22** [comment]
i want to work on this issue , please assign this issue to me
