### ISSUE TITLE
Track win/loss/draw records

### ISSUE THREAD

**Issue by iamparas0** [iamparas0/TIC-TAC-TOE#23]
![Screenshot (42)](https://github.com/user-attachments/assets/dc813774-571e-4fa1-be6d-f2ac9e282bbd)
Create a feature that keeps track of how many games have been won, lost, or ended in a draw.

**Comment by 4F24L** [comment]
Can you assign me for this issue ?

**Comment by Mahima-2404** [comment]
I am interested and capable.Please assign me this issue.

**Comment by Varsha567** [comment]
hii @iamparas0  could you please assign this to me?

**Comment by iamparas0** [comment]
> Can you assign me for this issue ?

go for it , please put a short video or ss before pr

**Comment by 4F24L** [comment]
> > Can you assign me for this issue ?
> 
> go for it , please put a short video or ss before pr

![image](https://github.com/user-attachments/assets/bad4f426-bbf7-42a7-8e9f-cd7961c1aeaf)

**Comment by 4F24L** [comment]
Can you add level2 for this issue??
