### ISSUE TITLE
Add an AI tab in the website

### ISSUE THREAD

**Issue by skanarul8002** [iamparas0/TIC-TAC-TOE#258]
I want to integrate a chatbot (AI assistant) into the Tic Tac Toe website that can:

1. Interact with players and provide tips or guidance about the game.
2. Answer frequently asked questions about how the game works, including the rules and strategies.
3. Engage players with fun facts or offer help when players seem confused during gameplay.

The AI tab will open a chatbot window where users can type in their questions or comments, and the chatbot will respond in real time.

**Comment by Anushka-kar** [comment]
hello @Dharshini3011 , can u please assigne me this work . I want to work on it .

**Comment by RAVICHANDRALS507** [comment]
I wan to work on this issue can you assign to me

**Comment by skanarul8002** [comment]
@Dharshini3011, please assign me bcz without assign is not considered in gssoc-ext. I am working on it.

**Comment by Dharshini3011** [comment]
@skanarul8002 start working on it and share your progress.

**Comment by skanarul8002** [comment]
Yeah sure
