### ISSUE TITLE
Enhanced APP.js And APP.css 

### ISSUE THREAD

**Issue by rimmon1234** [iamparas0/TIC-TAC-TOE#26]
The renderCell function now includes a key prop, a best practice when rendering lists in React.

Winner Message:
The winner message now accounts for a draw, enhancing user feedback.

A soft background color (#E3F2FD) creates a calming environment.

The main container (.app) has a white background with rounded corners and a subtle shadow for a card-like appearance.

Grid Layout:
The game board is organized into a grid using CSS Grid. This ensures that the cells are evenly spaced and responsive.

Cell Styling:
Cells have a soft background, rounded corners, and a border that changes on hover. This enhances interactivity.
A scaling effect on hover gives a responsive feel to the cells.

Winner Message:
The winner message is emphasized with a larger font size and color, making it clear to the player.

Buttons:
The restart button is styled with a matching color scheme and a hover effect that darkens the button, enhancing user experience.

Typography:
The Poppins font is used for a clean, modern look.

**Comment by iamparas0** [comment]
> The renderCell function now includes a key prop, a best practice when rendering lists in React.
> 
> Winner Message: The winner message now accounts for a draw, enhancing user feedback.
> 
> A soft background color (#E3F2FD) creates a calming environment.
> 
> The main container (.app) has a white background with rounded corners and a subtle shadow for a card-like appearance.
> 
> Grid Layout: The game board is organized into a grid using CSS Grid. This ensures that the cells are evenly spaced and responsive.
> 
> Cell Styling: Cells have a soft background, rounded corners, and a border that changes on hover. This enhances interactivity. A scaling effect on hover gives a responsive feel to the cells.
> 
> Winner Message: The winner message is emphasized with a larger font size and color, making it clear to the player.
> 
> Buttons: The restart button is styled with a matching color scheme and a hover effect that darkens the button, enhancing user experience.
> 
> Typography: The Poppins font is used for a clean, modern look.

Go ahead  , please put ss of before and after pr

**Comment by iamparas0** [comment]
> > The renderCell function now includes a key prop, a best practice when rendering lists in React.
> > Winner Message: The winner message now accounts for a draw, enhancing user feedback.
> > A soft background color (#E3F2FD) creates a calming environment.
> > The main container (.app) has a white background with rounded corners and a subtle shadow for a card-like appearance.
> > Grid Layout: The game board is organized into a grid using CSS Grid. This ensures that the cells are evenly spaced and responsive.
> > Cell Styling: Cells have a soft background, rounded corners, and a border that changes on hover. This enhances interactivity. A scaling effect on hover gives a responsive feel to the cells.
> > Winner Message: The winner message is emphasized with a larger font size and color, making it clear to the player.
> > Buttons: The restart button is styled with a matching color scheme and a hover effect that darkens the button, enhancing user experience.
> > Typography: The Poppins font is used for a clean, modern look.
> 
> Go ahead , please put ss of before and after pr

please fork new updated repo and make changes in it and put ss before pr so i can verify
