### ISSUE TITLE
Adding  Footer.

### ISSUE THREAD

**Issue by foreshubham** [iamparas0/TIC-TAC-TOE#27]
Adding a Navbar and a footer to this TIC-TAC-TOE will improve the UI much better and can add few more games to it. Games like PAC-MAN, Snake game etc.
![image](https://github.com/user-attachments/assets/bb3c37bf-3fc9-4f62-b1c9-967f24548775)
![image](https://github.com/user-attachments/assets/388c57a4-a523-4553-bd53-e8fdd0852834)

**Comment by foreshubham** [comment]
Assign this task to me. Please mark the label hacktoberfest, hacktoberfest-accepted, gssoc, and gssoc-extd

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by iamparas0** [comment]
> you can assign that task to me under gssoc-ext and hacktoberfest label..

go for footer only , please put ss before pr and update me as well

**Comment by iamparas0** [comment]
> Adding a Navbar and a footer to this TIC-TAC-TOE will improve the UI much better and can add few more games to it. Games like PAC-MAN, Snake game etc. ![image](https://private-user-images.githubusercontent.com/130773338/373125714-bb3c37bf-3fc9-4f62-b1c9-967f24548775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODE5NzUsIm5iZiI6MTcyODM4MTY3NSwicGF0aCI6Ii8xMzA3NzMzMzgvMzczMTI1NzE0LWJiM2MzN2JmLTNmYzktNGY2Mi1iMWM5LTk2N2YyNDU0ODc3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMDAxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTVlZTAwYmE3MmQ1NmYzMGMwM2NmOTFkYTRkNTRhOWI3YTA0MjMxNTYxMDY5ZGM1MDJmYjRhZWQ0MTIxZTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ehmt7ZKUDHpb87FKuMB0iOXbr2I_ub6CPBheWlc8WxU) ![image](https://private-user-images.githubusercontent.com/130773338/373125731-388c57a4-a523-4553-bd53-e8fdd0852834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODE5NzUsIm5iZiI6MTcyODM4MTY3NSwicGF0aCI6Ii8xMzA3NzMzMzgvMzczMTI1NzMxLTM4OGM1N2E0LWE1MjMtNDU1My1iZDUzLWU4ZmRkMDg1MjgzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMDAxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzVjY2FlZjk5ZTAzNTJhNGZjNGJhZGRhMTE5ZGJlYzUyMTA3ZDZkZjE4YjI1YTk1YTkzYTg1YTA3YzRiODBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.42Z8E3u1mIdDecPscLUNbWZMnstSoQzpzYzuotRode8)

due lots of contributor here i cant assign multiple task for same person

**Comment by SaanyaGarg5** [comment]
> > you can assign that task to me under gssoc-ext and hacktoberfest label..
> 
> go for footer only , please put ss before pr and update me as well

okay

**Comment by SaanyaGarg5** [comment]
@iamparas0 
I have completed the task..
pls go through it and let me know..
