### ISSUE TITLE
[Feature Request]: Add Functionality to Save Highest Score in Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by akansha204** [iamparas0/TIC-TAC-TOE#29]
Hi @iamparas0 
I want to implement a feature to track and save the highest score for Player 1 and Player 2 in a Tic-Tac-Toe game. The score should persist until the page is refreshed and be updated whenever a player achieves a new high score.

Proposed Implementation:

Use LocalStorage to store and retrieve the highest score for both players.
When a game ends, check the winner's score against the stored high score, and update if the new score is higher.
Display the highest score for each player on the game screen

Please assign this issue to me under gssoc'24 (extd)

**Comment by iamparas0** [comment]
> Hi @iamparas0 I want to implement a feature to track and save the highest score for Player 1 and Player 2 in a Tic-Tac-Toe game. The score should persist until the page is refreshed and be updated whenever a player achieves a new high score.
> 
> Proposed Implementation:
> 
> Use LocalStorage to store and retrieve the highest score for both players. When a game ends, check the winner's score against the stored high score, and update if the new score is higher. Display the highest score for each player on the game screen
> 
> Please assign this issue to me under gssoc'24 (extd)

go for it and please provide a short video of before and after

**Comment by akansha204** [comment]
Okay sure !

**Comment by Kavish-Paraswar** [comment]
Given my strong background in HTML, CSS, and JavaScript, I would like to request that this task be assigned to me.

**Comment by akansha204** [comment]
Hi @Kavish-Paraswar this issue is already assigned to me and i have started working on it. Kindly raise new issue

**Comment by akansha204** [comment]
https://github.com/user-attachments/assets/6e46b16e-2f4a-4815-9ec7-a488ecb06335

@iamparas0
