### ISSUE TITLE
Adding a transition to nav bar 

### ISSUE THREAD

**Issue by aditiverma-21** [iamparas0/TIC-TAC-TOE#290]
![image](https://github.com/user-attachments/assets/07e2f848-19e3-42a1-ab57-6e01fc3b3ba9)
I want to add the enhanced nav bar hover feature with the same color palette.
![image](https://github.com/user-attachments/assets/cbc47f0c-3efd-4b64-bf4b-46ebe0a84e59)

**Comment by DarshiniKurasa** [comment]
You can assign this to me.
I would like to work on this.
