### ISSUE TITLE
improvement in design

### ISSUE THREAD

**Issue by Mahy-31** [iamparas0/TIC-TAC-TOE#3]
As a UI/UX web designer, I believe that this website can be improved in the design part. I kindly request you to assign me this issue.

**Comment by Payel647** [comment]
i want to work on this issue

**Comment by iamparas0** [comment]
> As a UI/UX web designer, I believe that this website can be improved in the design part. I kindly request you to assign me this issue.

can you please specify about your design so i can assing you for that level please put screenshot if needed.

**Comment by Mahy-31** [comment]
The page looks so plain. Adding some attractive elements like change in background, using a color palette or having a landing page from which we can navigate to this
