### ISSUE TITLE
[Enhance]: enhancing the UI of the website .

### ISSUE THREAD

**Issue by Jashwanth-rit** [iamparas0/TIC-TAC-TOE#304]
Description:
Enhance the overall user interface of the website to provide a more modern, attractive, and user-friendly experience.

Benefits:

- Enhances user satisfaction and engagement.
- Increases retention rates by providing a pleasant browsing experience.

![Screenshot 2024-10-18 222845](https://github.com/user-attachments/assets/e76f0610-74d4-46fa-ac44-fc438773d1e7)

@iamparas0 add Gssoc and hacktoberfest tag , and assign me.

**Comment by Anushka1805** [comment]
@iamparas0 please assign me this issue
