### ISSUE TITLE
Footer overlapping with body text

### ISSUE THREAD

**Issue by biswa2005** [iamparas0/TIC-TAC-TOE#319]
the footer is overlapping with the body text in the game. this is looking pretty bad.
![image](https://github.com/user-attachments/assets/4d066fa8-a7b0-450d-b3f9-a19ae6ec5753)

**Comment by biswa2005** [comment]
please assign me this issue I can fix this.

**Comment by monalisas21** [comment]
Please assign this to me. I try making the footer look good.
