### ISSUE TITLE
Add a Light/Dark Mode Toggle

### ISSUE THREAD

**Issue by prishsha** [iamparas0/TIC-TAC-TOE#32]
I would like to add a button which will give the user the option to toggle between light/dark mode improving user experience. Kindly assign it to me under the label gssoc-ext and hacktoberfest-accepted along with the level of the problem. Thank you!

**Comment by iamparas0** [comment]
> I would like to add a button which will give the user the option to toggle between light/dark mode improving user experience. Kindly assign it to me under the label gssoc-ext and hacktoberfest-accepted along with the level of the problem. Thank you!

go for it and present a proper presentation on ss , good luck!

**Comment by saiprasanna56** [comment]
I'd like to contribute to your website!!
I want to add toggle button which toggles between dark mode and bright mode
CAN YOU ASSIGN THIS TO ME!! @iamparas0

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gssoc-ext and hacktoberfest label..

**Comment by prishsha** [comment]
![image](https://github.com/user-attachments/assets/003d4fd2-ae32-473c-be32-17bf5c994341)
![image](https://github.com/user-attachments/assets/61d21c1d-5f60-40a0-a27a-9acd6ddd79ed)

- [ ] Added toggle button
- [ ] Added dark mode UI/UX

Can i generate a pull request for the code?

**Comment by iamparas0** [comment]
> ![image](https://private-user-images.githubusercontent.com/143835467/373654672-003d4fd2-ae32-473c-be32-17bf5c994341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjA4OTYsIm5iZiI6MTcyODA2MDU5NiwicGF0aCI6Ii8xNDM4MzU0NjcvMzczNjU0NjcyLTAwM2Q0ZmQyLWFlMzItNDczYy1iZTMyLTE3YmY1Yzk5NDM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjQ5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODg4MzVkMjAyMWIwYTFhMGZlNmE4NWQ2MjgwN2VhZWViMGQwZmVmYjAyMWMwZGM5NWU2Mjg1ODQxZjEwYzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dIfBO9F29x3YOW3TV0_Z1mpegJzfurP2ckzIQztH8l8) ![image](https://private-user-images.githubusercontent.com/143835467/373654792-61d21c1d-5f60-40a0-a27a-9acd6ddd79ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjA4OTYsIm5iZiI6MTcyODA2MDU5NiwicGF0aCI6Ii8xNDM4MzU0NjcvMzczNjU0NzkyLTYxZDIxYzFkLTVmNjAtNDBhMC1hMjdhLTlhY2Q2ZGRkNzllZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQxNjQ5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZTRmNzU0NzM2ODM3YTViMmIyYzFiMWNkNGI2OTdjNzhiMzBlMGJmMzcwNTVmM2IwYzA2MmI3OTFiYzllNWU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cxqBLrRPghNA4_i3iBpqEZ0ZdBbL3jVuIbI2n8Rc5VE)
> 
> * [x]  Added toggle button
> * [x]  Added dark mode UI/UX
> 
> Can i generate a pull request for the code?

Great work , please go ahead

**Comment by iamparas0** [comment]
> ![image](https://private-user-images.githubusercontent.com/143835467/373654672-003d4fd2-ae32-473c-be32-17bf5c994341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTYyOTIsIm5iZiI6MTcyODExNTk5MiwicGF0aCI6Ii8xNDM4MzU0NjcvMzczNjU0NjcyLTAwM2Q0ZmQyLWFlMzItNDczYy1iZTMyLTE3YmY1Yzk5NDM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwODEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzFkNDdlZjQ1ZTkxMjY3YmUzMjVhN2FkYzNlZTJkOWJmYmRmYTBlYTVmYTg1ZTFlZDkxNjkwNmViYWM5OGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kIKk2yjjVabzXqaefjyK50CiY_yYshxpoi1zACLUdGY) ![image](https://private-user-images.githubusercontent.com/143835467/373654792-61d21c1d-5f60-40a0-a27a-9acd6ddd79ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMTYyOTIsIm5iZiI6MTcyODExNTk5MiwicGF0aCI6Ii8xNDM4MzU0NjcvMzczNjU0NzkyLTYxZDIxYzFkLTVmNjAtNDBhMC1hMjdhLTlhY2Q2ZGRkNzllZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwODEzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzdjZTE5YWRkNWUwNTUxMjY0YzU2M2NmYTY0YjBmM2IxZjc5YmE1M2VhMjM4YTdmZmQ4NDc3OGNmNzgzN2Q0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WxSw_zkNxIMQKORNb3a-EcPcZ8mLO6pLynzu_Teajuc)
> 
> * [x]  Added toggle button
> * [x]  Added dark mode UI/UX
> 
> Can i generate a pull request for the code?

thanks for the great contribution , hope this helps you to utilise your experience . best of the luc for future!
