### ISSUE TITLE
[⭐FEATURE] Add a new page to display all contributors

### ISSUE THREAD

**Issue by Subhajit-2023-44** [iamparas0/TIC-TAC-TOE#320]
I want to add a page to showcase all the contributors of this website..

@iamparas0  please assign me this task.

![image](https://github.com/user-attachments/assets/803810d7-555d-4a20-bd56-e4cb05b50cc1)

**Comment by Subhajit-2023-44** [comment]
@iamparas0

**Comment by iamparas0** [comment]
no need
