### ISSUE TITLE
[Feature Request] AI Opponent

### ISSUE THREAD

**Issue by TheRaj71** [iamparas0/TIC-TAC-TOE#34]
### Description:
I propose adding an AI player to the Tic-Tac-Toe game, allowing users to play against a computer opponent. This feature will increase the game's replayability and enhance user engagement.

### Requirements:

1. **AI Game Logic:**
   - The AI should make optimal moves based on the current board state.
   - It should be able to identify winning moves and block the player from winning.

2. **User Interface:**
   - Add an option in the game menu to select an AI opponent.
   - Provide a visual indicator when the AI is making a move.

### Benefits:
- Improves user engagement with a challenging single-player mode.
- Attracts players who prefer AI opponents over human players.

### Next Steps:
- Review AI algorithms like Minimax for optimal implementation.

  
Thank you for considering this feature request.
If Possible kindly assign this issue to me under hacktober and gssco tag!

**Comment by iamparas0** [comment]
> ## Feature Request: AI Player for Tic-Tac-Toe
> ### Description:
> I propose adding an AI player to the Tic-Tac-Toe game, allowing users to play against a computer opponent. This feature will increase the game's replayability and enhance user engagement.
> 
> ### Requirements:
> 1. **AI Game Logic:**
>    
>    * The AI should make optimal moves based on the current board state.
>    * It should be able to identify winning moves and block the player from winning.
> 2. **User Interface:**
>    
>    * Add an option in the game menu to select an AI opponent.
>    * Provide a visual indicator when the AI is making a move.
> 
> ### Benefits:
> * Improves user engagement with a challenging single-player mode.
> * Attracts players who prefer AI opponents over human players.
> 
> ### Next Steps:
> * Review AI algorithms like Minimax for optimal implementation.
> 
> Thank you for considering this feature request. If Possible kindly assign this issue to me under hacktober and gssco tag!
sounds good 
go for it , please remember all the changes will be in new branch
