### ISSUE TITLE
Lack of Cell Hover Effect 

### ISSUE THREAD

**Issue by Vishwajeet594** [iamparas0/TIC-TAC-TOE#36]
### Description:
**The cells on the Tic Tac Toe board do not provide any visual feedback when a player hovers over them, making the interaction less intuitive**.

### Request:
**Add a hover effect (e.g., changing the cell color or showing a light preview of the mark) when a player hovers over an empty cell to improve user feedback.**

**Comment by arpit74170** [comment]
Please assign it to me
Thanks.

**Comment by Vishwajeet594** [comment]
guys find ur own issue
