### ISSUE TITLE
Improving UI of the Rules.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [iamparas0/TIC-TAC-TOE#40]
the rules section feels a little empty , i can refactor it to make it look more pleasing. Can you please assign me this issue.
Thank you!

@can you please assign me this task @iamparas0 
<img width="919" alt="Screenshot 2024-10-05 at 7 00 53 PM" src="https://github.com/user-attachments/assets/b1a22693-24ed-49ba-9310-15c63857abaa">

**Comment by arpit74170** [comment]
Please assign it to me
Thanks.
