### ISSUE TITLE
Add Draw in case of no winners 

### ISSUE THREAD

**Issue by subin-shk** [iamparas0/TIC-TAC-TOE#42]
There is no "Draw" appearing in case of no winners. And the rules would look better if they are centered.

![image](https://github.com/user-attachments/assets/7327544a-681b-49cb-b70f-9edf933aa55a)

**Comment by subin-shk** [comment]
gssoc-extd, hacktoberfest

**Comment by Mirnalkishor** [comment]
- Implemented restart button to reset the game state
- Added draw condition and message when game ends in a tie
- Updated CSS for restart button and winner/draw messages
- add animation after winning.

 ![image](https://github.com/user-attachments/assets/59f997d2-30d7-476f-932c-60f473ebdafb)

**Comment by subin-shk** [comment]
i was the one who raised the issue. dont assign this to anyone but me
