### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by juniorcoder02** [iamparas0/TIC-TAC-TOE#5]
Hey I can write better readme.md for you project can you assign to me under the gssoc'24 extended

**Comment by BVPKARTHIKEYA** [comment]
Hey I would love to 
write better readme.md for you project can you assign to me under the gssoc'24 extended program

**Comment by laxmi47** [comment]
@iamparas0 I'd like contribute and make a great readme.md. can you assign this to me under the gssoc'24 extended program!
