### ISSUE TITLE
Bug Report: No Tie Game Announcement in Tic-Tac-Toe

### ISSUE THREAD

**Issue by satyasootar** [iamparas0/TIC-TAC-TOE#59]
When the game ends in a tie (all spots filled and no winner), the game does not display a "Tie" or "Draw" announcement. The player is left without any indication that the game ended in a draw, which may cause confusion. Please allow me to fix that
![image](https://github.com/user-attachments/assets/47a1fc75-cfc3-49ac-800b-3b2c4367f6b2)

**Comment by iamparas0** [comment]
> When the game ends in a tie (all spots filled and no winner), the game does not display a "Tie" or "Draw" announcement. The player is left without any indication that the game ended in a draw, which may cause confusion. Please allow me to fix that ![image](https://private-user-images.githubusercontent.com/130484055/373855822-47a1fc75-cfc3-49ac-800b-3b2c4367f6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxOTgyMjIsIm5iZiI6MTcyODE5NzkyMiwicGF0aCI6Ii8xMzA0ODQwNTUvMzczODU1ODIyLTQ3YTFmYzc1LWNmYzMtNDlhYy04MDBiLTNiMmM0MzY3ZjZiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwNjU4NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmI0ZDY3Njk0ZTVmZGY2ZjI1YzI1ZDBiMDNlMTdiNDg4ODcwZmIzZjA1YWQ2NWUzZjQ4MTU5YmJkOTRjMWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ekO5pi8jWRDBf71sHsnpgzlQFw2OrsM1wr7ky8JxxWw)

its already fixed by someone else!
