### ISSUE TITLE
[New Feature]: Adding Dark Mode

### ISSUE THREAD

**Issue by Harshitha-Annam** [iamparas0/TIC-TAC-TOE#82]
It seems like the current version of the tic-tac-toe game only contains light mode, it would be more userfriendly if it also has an option of choosing darkmode.
Please assign this task for me.

- [x] I am a GSSOC Etxd Contributor.

**Comment by iamparas0** [comment]
> It seems like the current version of the tic-tac-toe game only contains light mode, it would be more userfriendly if it also has an option of choosing darkmode. Please assign this task for me.
> 
> * [x]  I am a GSSOC Etxd Contributor.

dark mode is available !
